# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='郵箱')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/usrimg', verbose_name='用戶頭像')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'author',
                'ordering': ['-age', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='書名')),
                ('publication_date', models.DateField(verbose_name='出版日期')),
            ],
            options={
                'verbose_name': '圖書',
                'verbose_name_plural': '圖書',
                'db_table': 'book',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='匿名', max_length=30, verbose_name='名稱')),
                ('address', models.CharField(max_length=60, verbose_name='地址')),
                ('city', models.CharField(max_length=30, verbose_name='所在城市')),
                ('country', models.CharField(max_length=30, verbose_name='國家')),
                ('website', models.URLField(verbose_name='網址')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'db_table': 'publisher',
            },
        ),
    ]
