# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_wife_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '妻子', 'verbose_name_plural': '妻子'},
        ),
        migrations.AlterField(
            model_name='wife',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Author', verbose_name='相公'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
