# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_author_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='index.Author', verbose_name='作者'),
        ),
    ]
